name: My Form
about: A form for creating issues

fields:
  - name: team
    label: Which team are you on?
    type: dropdown
    options:
      - Team A
      - Team B
  - &problem_description
    name: problem_description
    label: Problem Description
    type: textarea
    required: true
  - *background

{% if team == "Team A" %}
  - &background
    name: background
    label: Background
    type: textarea
{% endif %}
{% if team == "Team B" %}
  - &background
    name: background
    label: Background
    type: textarea
{% endif %}
