name: Issue Template - 🧠 Backend
description: File a bug report for Backend
title: "<ENTER ISSUE TITLE>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Manually add "🧠 Backend" on Projects -->
        Please fill the fields below accordingly
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A description of what happened, how to reproduce, how it affects usage
    validations:
      required: true
  - type: dropdown
    id: env
    attributes:
      label: Enviroment
      description: Enviroment where issue was reproduced
      multiple: true
      options:
        - Prod
        - Beta
        - Staging
        - Dev
        - Local/ Other
    validations:
      required: true
  - type: textarea
    id: realestate
    attributes:
      label: Realestate
      description: Realestate/ Site where the issue occurred
    validations:
      required: false
