name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: project
    attributes:
      label: Select Project
      description: Choose the relevant project associated to the issue found
      options:
        - FE/JSE
        - Native
        - Registration
        - Backend
        - Unities
        - OpsSW and Tools
        - Colin
    validations:
      required: true
  - type: checkboxes
    id: choice
    trigger:
      action: show
      field: project
      condition: 'value[FE/JSE]'
    attributes:
      label: Did you choose FE/JSE
      description: Say the truth
      options:
        - label: Yes
        - label: No
  - type: checkboxes
    id: choice
    trigger:
      action: show
      field: project
      condition: 'value[Native]'
    attributes:
      label: Did you choose Native
      description: Say the truth
      options:
        - label: Yes
        - label: No
  - type: checkboxes
    id: choice
    trigger:
      action: show
      field: project
      condition: 'value[Registration]'
    attributes:
      label: Did you choose Registration
      description: Say the truth
      options:
        - label: Yes
        - label: No
