name: Issue Template - 🍭 JSE / 🕸️ Frontend
description: File a bug report for either JSE or Frontend
title: "<ENTER ISSUE TITLE>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Manually add "🍭 JSE" OR "🕸️ Frontend" on Projects -->
        Please fill the fields below accordingly
  - type: checkboxes
    id: reproducibility
    attributes:
      label: The issue is reproducible
      description: Before proceeding, assert the issue is reproducible
      options:
        - label: The issue was reproduced at least 3 times
          required: true
        - label: Reproducible on DOOM (VCC emulator)
          required: false
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A description of what happened, how to reproduce, how it affects usage
      placeholder: |
        #####Issue description:


        #####How to reproduce:

        #####Recording of the bug (drag file or add link):

        #####Developer options screenshot
        ###### Display all links under Developer Options under General Information (tap 7 times on the title) within Vera System Information 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs from Dev Tools
      description: Copy and paste any relevant log output from either Console or Network tabs on Chrome dev tools
      render: JavaScript
