name: OpsSW and Tools Issue Template
description: File a bug report for OpsSW and Tools
title: "<REPLACE WITH ISSUE TITLE>"
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please fill the fields below accordingly
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A description of what happened, how to reproduce, how it affects usage
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot of the bug
      description: A screenshot or a video capture from the time the bug happened or after the event happaned, if relevant also a screenshot of the expected behavior, screenshot of the console/network tab at the time of the error
    validations:
      required: false
  - type: textarea
    id: Environment
    attributes:
      label: Environment information
      description: Link to the frontend where it happened that includes, Site, Location, Selected scan points etc., Additional system information like OS, browser, and the output of commands such as window.$3d.module.threeHelpers.getAllInformation
    validations:
      required: true
