name: Issue Template - 🍭 JSE / 🕸️ Frontend
description: File a bug report for either JSE or Frontend
title: "<ENTER ISSUE TITLE>"
labels: ["bug", "mst"]
body:
  - type: markdown
    attributes:
      value: |
        Manually add "🍭 JSE" OR "🕸️ Frontend" on Projects -->
        
        [### Check this is NOT a DUPLICATE ###](https://github.com/users/avik-resonai/projects/1)

        Please fill the fields below accordingly
  - type: checkboxes
    id: reproducibility
    attributes:
      label: The issue is reproducible
      description: Before proceeding, assert the issue is reproducible
      options:
        - label: The issue was reproduced at least 3 times
          required: true
        - label: Reproducible on DOOM (VCC emulator)
          required: false
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A description of what happened, how to reproduce, how it affects usage
    validations:
      required: true
  - type: textarea
    id: screenrecording
    attributes:
      label: Recording of the bug
      description: A screenshot or a video capture from the time the bug happened or after the event happaned. It is not a must but will be highly appreciated 
      placeholder: Drag file here or add screenshot link
    validations:
      required: false
  - type: textarea
    id: settings
    attributes:
      label: Developer options screenshot
      description: Display all links under Developer Options under General Information (tap 7 times on the title) within Vera System Information 
      placeholder: Drag file here or add screenshot link
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs from Dev Tools
      description: Copy and paste any relevant log output from either Console or Network tabs on Chrome dev tools
      render: JavaScript
