name: Issue Template - 🤳 Native App
description: File a bug report for Native App
title: "<ENTER ISSUE TITLE>"
labels: ["bug","🤳 Native App"]
body:
  - type: markdown
    attributes:
      value: |
        Manually add "🤳 Native App" on Projects -->

        [### Check this is NOT a DUPLICATE ###](https://github.com/orgs/resonai/projects/4)
        
        Please fill the fields below accordingly
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A description of what happened, how to reproduce, how it affects usage
      value: |
        --------
        [Description of the issue]:

        --------
        [How to Reproduce]:
        1.
        2.
        3.
        ....

        --------
        [Screenshot / Recording]:
        (Drag & drop media in OR enter link)
    validations:
      required: true
