name: Issue Template - 🤳 Native App
description: File a bug report for Native App
title: "<ENTER ISSUE TITLE>"
labels: ["bug","🤳 Native App"]
body:
  - type: markdown
    attributes:
      value: |
        Manually add "🤳 Native App" on Projects -->

        [### Check this is NOT a DUPLICATE ###](https://github.com/orgs/resonai/projects/4)
        
        Please fill the fields below accordingly
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A description of what happened, how to reproduce, how it affects usage
      value: |
        [Description of the issue]:

        --------
        [How to Reproduce]:
        1.
        2.
        3.
        ....

        --------
        [Screenshot / Recording]:
        (Drag & drop media in OR enter link)
    validations:
      required: true
  - type: dropdown
    id: env
    attributes:
      label: Operating system
      description: OS where the issues was experienced on
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: input
    id: crashlytics
    attributes:
      label: Crashlytics / crash report
      description: Link to the report
    validations:
      required: false
  - type: textarea
    id: settings
    attributes:
      label: Settings screenshot
      description: Show System Information under Vera settings 
      placeholder: Drag file here or add screenshot link
    validations:
      required: true
